version: '2'
services:
  database:
    container_name: database
    image: postgres:latest
    ports:
      - "5600:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=senha
    # volumes:
    #  - .\database\data:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      context: test-dev-back
      dockerfile: Dockerfile
    image: backend:latest
    depends_on:
      - "database"
    ports:
      - "5500:80"
    # command: ["php", "-S", "0.0.0.0:4000", "test.php"]

  frontend:
    container_name: frontend
    build:
      context: test-dev-front
      dockerfile: Dockerfile
    image: fronted:latest
    depends_on:
      - "backend"
    ports:
      - "80:80"