version: '2'
services:
  database:
    container_name: database
    image: postgres:latest
    expose:
      - "5600"
    ports:
      - "5600:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_DB=devtest
      - POSTGRES_PASSWORD=senha
    networks: 
      - devtest-network
    volumes:
     - ./database:/docker-entrypoint-initdb.d

  backend:
    container_name: backend
    image: phalconphp/php-apache:ubuntu-16.04
    depends_on:
      - "database"
    expose:
      - "5500"
    ports:
      - "5500:80"
    volumes:
     - ./test-dev-back:/app
    networks: 
      - devtest-network
    
  # frontend:
  #   container_name: frontend
  #   build:
  #     context: test-dev-front
  #     dockerfile: Dockerfile
  #   image: frontend:latest
  #   depends_on:
  #     - "backend"
  #   ports:
  #     - "80:80"
  #   networks: 
  #     - devtest-network

networks: 
  devtest-network: